redmine: 
  image: sameersbn/redmine
  hostname: redmine
  ports: 
    - "10080:80" 
  volumes_from: 
    - redmine-storage
  links: 
    - mysql
    - memcached
    - svn
    
svn:
  image: hidetarou2013/centos6-apache:SVN_repo1
  hostname: svn
  expose: 
    - "80" 
    - "443" 
  volumes: 
    - /home/vagrant/web-contents/:/var/www/html/
  command: etc/init.d/httpd start && /etc/rc.d/init.d/svnserve restart
  
redmine-storage:
 image: hidetarou2013/redmine-storage
 
mysql: 
  image: sameersbn/mysql:latest
  hostname: mysql
  environment: 
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  ports: 
    - "3306:3306" 
  volumes_from: 
    - mysql-storage

mysql-storage:
 image: hidetarou2013/mysql-storage

memcached:
 image: memcached
